services:
  scholarbite-gateway:
    image: ghcr.io/hkuds/nanobot:latest
    container_name: scholarbite
    restart: unless-stopped
    volumes:
      - ~/.nanobot:/root/.nanobot
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: gateway

  scholarbite-cli:
    image: ghcr.io/hkuds/nanobot:latest
    container_name: scholarbite-cli
    profiles:
      - cli
    volumes:
      - ~/.nanobot:/root/.nanobot
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: chat
